### ISSUE TITLE
Provide the trained model

### ISSUE THREAD

**Issue by atifayaz99** [LidorPrototype/TableNetTable2df#1]
## You have provided the testing notebook which is great, but I don't see any models in the GitHub repo, can you upload the model.pth as well?

**Comment by LidorPrototype** [comment]
Hello, the model is too big for the GitHub repo, but you have all of the steps including articles in order to create such a model yourself mate, if you'll run into any problem in the process I would love to try and help you out 👍🏻

**Comment by atifayaz99** [comment]
I don't see any training notebook for a smooth training process. :'(

**Comment by LidorPrototype** [comment]
True, there is no notebook for the training process, it's all in Python files, you can use them all in one notebook if you prefer it that way.
Read the article I created on the medium website for that repo, all the steps are there (The link is in the repo description, it's the model article link, but the rest you can navigate from the article itself)

**Comment by atifayaz99** [comment]
Sure I will follow the blog instructions, if I face any issues I will ping you

**Comment by atifayaz99** [comment]
is it poosible that you can upload it to google drive and provide the link?
